# Generated by Django 4.1.3 on 2023-01-16 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='crated',
            new_name='created',
        ),
    ]
