# Generated by Django 4.1.3 on 2023-01-17 07:42

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_rename_crated_gallery_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'gallery', 'verbose_name_plural': 'gallery'},
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to=utils.upload_image_path, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=150, verbose_name='title'),
        ),
    ]
