# Generated by Django 4.1.3 on 2022-12-02 14:17

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='category',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='categories.categories', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.ImageField(upload_to=utils.upload_image_path, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='video'),
        ),
    ]
