# Generated by Django 4.1.3 on 2023-01-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogs_selected_blog_blogs_show_on_slider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
