# Generated by Django 4.1.3 on 2023-01-02 13:33

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='body')),
                ('image', models.ImageField(upload_to=utils.upload_image_path, verbose_name='image')),
                ('video', models.FileField(blank=True, null=True, upload_to=utils.upload_video_path, verbose_name='video')),
                ('created_date', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('modified_date', django_jalali.db.models.jDateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('selected_service', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
