# Generated by Django 4.1.3 on 2023-01-24 14:06

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=200, verbose_name='site title')),
                ('telephone', models.CharField(blank=True, max_length=12, null=True, verbose_name='telephone')),
                ('mobile', models.CharField(max_length=12, verbose_name='mobile')),
                ('address', models.TextField(blank=True, null=True, verbose_name='address')),
                ('logo', models.ImageField(upload_to=utils.upload_image_path, verbose_name='logo')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('instagram_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='instagram id')),
                ('telegram_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='telegram id')),
            ],
        ),
    ]
